# This file was generated by GoReleaser. DO NOT EDIT.
cask "schepherd" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "81973b12d291de76355f8855e79b00fb1eadd22d74e74a4d6e5050b2910cf639"
      url "https://github.com/ovineko/schepherd/releases/download/v#{version}/schepherd_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0d6b1640c9fbb73694b78d8f79328b1328d7bf45f0cb89f71e1e83a2bdbf2f56"
      url "https://github.com/ovineko/schepherd/releases/download/v#{version}/schepherd_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "db8c7dd8d9ed1882c79d4bf2545a747964bf559c6c29c902cde0ab3140a152ac"
      url "https://github.com/ovineko/schepherd/releases/download/v#{version}/schepherd_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "635e88ea44035f3a749fb35f5190f8b1b6227ea5c730baec78ba70328ed3893d"
      url "https://github.com/ovineko/schepherd/releases/download/v#{version}/schepherd_#{version}_linux_amd64.tar.gz"
    end
  end

  name "schepherd"
  desc "Delivers pinned JSON Schemas from an OCI catalog to verified local files"
  homepage "https://schepherd.ovineko.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "schepherd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/schepherd"]
    end
  end

  # No zap stanza required
end
