# This file was generated by GoReleaser. DO NOT EDIT.
cask "schepherd" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "e99cb645929f3854a80b32fec69cf03dc367cfc4f096b3bfd85baa43e8c5f774"
      url "https://github.com/ovineko/schepherd/releases/download/v#{version}/schepherd_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f2e6d8169cc834399ff778ddfbaed1bd701d38c970403198ee594df3e073493b"
      url "https://github.com/ovineko/schepherd/releases/download/v#{version}/schepherd_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c62857638463242fa81b862b0b3708d209feb9155cd1a4d62b81214fb8f3c7ee"
      url "https://github.com/ovineko/schepherd/releases/download/v#{version}/schepherd_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1663bb2dca3a4241cf1ba8182ed1e846494d3dd11028a4863e969cad683ff5f3"
      url "https://github.com/ovineko/schepherd/releases/download/v#{version}/schepherd_#{version}_linux_amd64.tar.gz"
    end
  end

  name "schepherd"
  desc "Delivers pinned JSON Schemas from an OCI catalog to verified local files"
  homepage "https://schepherd.ovineko.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "schepherd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/schepherd"]
    end
  end

  # No zap stanza required
end
